# Generated by Django 5.2.10 on 2026-03-09 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_balance_due"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="payment_reference",
        ),
    ]
