# Generated by Django 5.2.10 on 2026-01-29 15:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "vehicle_type",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Plate number e.g. ABC-123DE",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "make_model",
                    models.CharField(
                        help_text="e.g. Toyota Hiace 2020", max_length=100
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(help_text="Total passenger seats"),
                ),
                (
                    "year_manufactured",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("amenities", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active/Available"),
                            ("maintenance", "In Maintenance"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_insured", models.BooleanField(default=False)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("roadworthiness_expiry_date", models.DateField(blank=True, null=True)),
                ("vehicle_images", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        limit_choices_to={"role": "vendor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        help_text="Choose a default type or create a custom one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="trips.vehicletype",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("departure_state", models.CharField(max_length=150)),
                (
                    "departure_city",
                    models.CharField(
                        help_text="Starting point e.g. Iyana-Ipaja", max_length=150
                    ),
                ),
                (
                    "destination_camp",
                    models.CharField(
                        help_text="Destination e.g. NYSC Camp, Iyana-Ipaja",
                        max_length=150,
                    ),
                ),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("estimated_arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "price_per_seat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("available_seats", models.PositiveSmallIntegerField(default=0)),
                (
                    "early_bird_discount_percentage",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("early_bird_deadline", models.DateField(blank=True, null=True)),
                (
                    "group_discount_percentage",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("refund_policy", models.TextField(blank=True)),
                ("luggage_allowance", models.CharField(blank=True, max_length=200)),
                ("special_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        limit_choices_to={"role": "vendor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="trips.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "trip",
                "ordering": ["departure_date", "departure_time"],
                "indexes": [
                    models.Index(
                        fields=["departure_date", "status"],
                        name="trip_departu_171f6a_idx",
                    ),
                    models.Index(
                        fields=["vendor", "status"], name="trip_vendor__ee13ac_idx"
                    ),
                ],
            },
        ),
    ]
