# Generated by Django 6.0.1 on 2026-01-13 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.PositiveSmallIntegerField(blank=True, help_text='Assigned seat number if applicable', null=True)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vendor.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, help_text='Assigned vehicle (can be set later)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vendor.vehicle')),
            ],
            options={
                'ordering': ['-booked_at'],
                'indexes': [models.Index(fields=['user', 'trip'], name='bookings_bo_user_id_04e395_idx'), models.Index(fields=['booking_status', 'payment_status'], name='bookings_bo_booking_450a97_idx'), models.Index(fields=['trip', 'booking_status'], name='bookings_bo_trip_id_b596cd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('seat_number__isnull', False)), fields=('trip', 'seat_number'), name='unique_seat_per_trip')],
            },
        ),
    ]
